/**
 * Machine-readable error codes returned in `error.code`.
 * Mirrors the set in the spec (BACKEND_PROMPT.md §8), plus our own-auth codes.
 */
export const ERROR_CODE = {
  // auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_OAUTH_TOKEN: 'INVALID_OAUTH_TOKEN',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  // otp / phone verification
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  // not found
  NOT_FOUND: 'NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  // validation / conflict
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  REDEMPTION_LIMIT_REACHED: 'REDEMPTION_LIMIT_REACHED',
  REDEMPTION_INVALID_CODE: 'REDEMPTION_INVALID_CODE',
  BUSINESS_TYPE_NOT_FOUND: 'BUSINESS_TYPE_NOT_FOUND',
  BUSINESS_TYPE_IMMUTABLE: 'BUSINESS_TYPE_IMMUTABLE',
  BUSINESS_TYPE_EXISTS: 'BUSINESS_TYPE_EXISTS',
  BUSINESS_TYPE_IN_USE: 'BUSINESS_TYPE_IN_USE',
  CATEGORY_NOT_IN_CATALOG: 'CATEGORY_NOT_IN_CATALOG',
  // listings
  DISCOUNT_TOO_HIGH: 'DISCOUNT_TOO_HIGH',
  FINAL_PRICE_INVALID: 'FINAL_PRICE_INVALID',
  ATTRIBUTES_SCHEMA_MISMATCH: 'ATTRIBUTES_SCHEMA_MISMATCH',
  // branch location
  LOCATION_OUT_OF_BOUNDS: 'LOCATION_OUT_OF_BOUNDS',
  DISTRICT_REGION_MISMATCH: 'DISTRICT_REGION_MISMATCH',
  LOCATION_DISTRICT_MISMATCH: 'LOCATION_DISTRICT_MISMATCH',
  DUPLICATE_BRANCH_LOCATION: 'DUPLICATE_BRANCH_LOCATION',
  // trade centers
  TRADE_CENTER_NOT_FOUND: 'TRADE_CENTER_NOT_FOUND',
  TRADE_CENTER_FIELD_INVALID: 'TRADE_CENTER_FIELD_INVALID',
  // infra
  RATE_LIMITED: 'RATE_LIMITED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
