/**
 * Machine-readable error codes returned in `error.code`.
 * Mirrors the set in the spec (BACKEND_PROMPT.md §8), plus our own-auth codes.
 */
export const ERROR_CODE = {
  // auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_OAUTH_TOKEN: 'INVALID_OAUTH_TOKEN',
  ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
  // otp / phone verification
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',
  // not found
  NOT_FOUND: 'NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  // validation / conflict
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  REDEMPTION_LIMIT_REACHED: 'REDEMPTION_LIMIT_REACHED',
  REDEMPTION_INVALID_CODE: 'REDEMPTION_INVALID_CODE',
  BUSINESS_TYPE_IMMUTABLE: 'BUSINESS_TYPE_IMMUTABLE',
  CATEGORY_NOT_IN_CATALOG: 'CATEGORY_NOT_IN_CATALOG',
  // infra
  RATE_LIMITED: 'RATE_LIMITED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
